[project]
name = "netbox-mcp"
version = "0.1.0"
description = "MCP server for NetBox"
dependencies = [
    "mcp",
    "pynetbox",
    "starlette",
    "uvicorn",
]

[project.scripts]
dev = "src.server:main"
